name: brainplot
channels:
  - conda-forge
  - defaults
  - janton01
dependencies:
  - python>=3.7
  - pip
  - matplotlib>=3.2.0
  - numpy>=1.14.0
  - scipy>=0.17
  - vtk-offscreen
  - mesalib
  - pip:
    - 'git+git://github.com/netneurolab/brainnotation.git#egg=brainnotation'
    - brainspace>=0.1.1
    - nibabel
    - nilearn>=0.7.0
    - sphinx>=2.0
    - sphinx_rtd_theme
    - sphinx-gallery
    - sphinx_argparse 